# Generated by Django 2.1.2 on 2018-11-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CorreoElectronico', models.CharField(max_length=100)),
                ('Run', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=50)),
                ('FechaNacimiento', models.DateField()),
                ('Telefono', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('Comuna', models.CharField(max_length=50)),
                ('TipoCasa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rescatados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombreresc', models.CharField(max_length=100)),
                ('RazaPredom', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
                ('image', models.FileField(default='SOME STRING', upload_to='albums')),
            ],
        ),
    ]
